In [2]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [3]:
credit_df = pd.read_csv('credit_card.csv')
credit_df.head()

,Ind_ID,GENDER,Car_Owner,Propert_Owner,CHILDREN,Annual_income,Type_Income,EDUCATION,Marital_status,Housing_type,Birthday_count,Employed_days,Mobile_phone,Work_Phone,Phone,EMAIL_ID,Type_Occupation,Family_Members
0,5008827,M,Y,Y,0,180000.0,Pensioner,Higher education,Married,House / apartment,-18772.0,365243,1,0,0,0,NaN,2
1,5009744,F,Y,N,0,315000.0,Commercial associate,Higher education,Married,House / apartment,-13557.0,-586,1,1,1,0,NaN,2
2,5009746,F,Y,N,0,315000.0,Commercial associate,Higher education,Married,House / apartment,NaN,-586,1,1,1,0,NaN,2
3,5009749,F,Y,N,0,NaN,Commercial associate,Higher education,Married,House / apartment,-13557.0,-586,1,1,1,0,NaN,2
4,5009752,F,Y,N,0,315000.0,Commercial associate,Higher education,Married,House / apartment,-13557.0,-586,1,1,1,0,NaN,2

In [4]:
credit_df_encoded = pd.get_dummies(data = credit_df, dtype = int)

In [5]:
credit_df_encoded.head()

,Ind_ID,CHILDREN,Annual_income,Birthday_count,Employed_days,Mobile_phone,Work_Phone,Phone,EMAIL_ID,Family_Members,...,Type_Occupation_Laborers,Type_Occupation_Low-skill Laborers,Type_Occupation_Managers,Type_Occupation_Medicine staff,Type_Occupation_Private service staff,Type_Occupation_Realty agents,Type_Occupation_Sales staff,Type_Occupation_Secretaries,Type_Occupation_Security staff,Type_Occupation_Waiters/barmen staff
0,5008827,0,180000.0,-18772.0,365243,1,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
1,5009744,0,315000.0,-13557.0,-586,1,1,1,0,2,...,0,0,0,0,0,0,0,0,0,0
2,5009746,0,315000.0,NaN,-586,1,1,1,0,2,...,0,0,0,0,0,0,0,0,0,0
3,5009749,0,NaN,-13557.0,-586,1,1,1,0,2,...,0,0,0,0,0,0,0,0,0,0
4,5009752,0,315000.0,-13557.0,-586,1,1,1,0,2,...,0,0,0,0,0,0,0,0,0,0

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
credit_df_encoded.corr()

,Ind_ID,CHILDREN,Annual_income,Birthday_count,Employed_days,Mobile_phone,Work_Phone,Phone,EMAIL_ID,Family_Members,...,Type_Occupation_Laborers,Type_Occupation_Low-skill Laborers,Type_Occupation_Managers,Type_Occupation_Medicine staff,Type_Occupation_Private service staff,Type_Occupation_Realty agents,Type_Occupation_Sales staff,Type_Occupation_Secretaries,Type_Occupation_Security staff,Type_Occupation_Waiters/barmen staff
Ind_ID,1.000000,0.032535,0.030147,0.022909,-0.055396,NaN,0.085794,0.008403,-0.037923,0.016950,...,-0.001947,-0.001929,0.006502,0.044050,0.066078,0.018468,0.006714,0.023849,0.064955,0.035227
CHILDREN,0.032535,1.000000,0.078497,0.279716,-0.219095,NaN,0.035014,-0.004908,0.025776,0.890248,...,0.022808,-0.007826,0.052493,0.029932,0.031794,0.027202,0.017414,0.014061,-0.002111,-0.015601
Annual_income,0.030147,0.078497,1.000000,0.111638,-0.160175,NaN,-0.071171,-0.006439,0.122320,0.050957,...,-0.024740,-0.040765,0.277783,-0.052991,0.008424,0.003553,-0.031391,-0.019668,-0.010219,-0.034954
Birthday_count,0.022909,0.279716,0.111638,1.000000,-0.619039,NaN,0.174687,-0.029215,0.166749,0.266527,...,0.132580,0.002079,0.104158,-0.015466,0.027886,0.041609,0.143097,0.002621,-0.042135,0.041152
Employed_days,-0.055396,-0.219095,-0.160175,-0.619039,1.000000,NaN,-0.231184,-0.003403,-0.118268,-0.238705,...,-0.206216,-0.034020,-0.139870,-0.085226,-0.047977,-0.016329,-0.129966,-0.034856,-0.056413,-0.025315
Mobile_phone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Work_Phone,0.085794,0.035014,-0.071171,0.174687,-0.231184,NaN,1.000000,0.352439,-0.009594,0.072228,...,0.013685,0.044546,0.032106,-0.003606,0.007083,0.025875,0.003678,0.002678,-0.015155,-0.001123
Phone,0.008403,-0.004908,-0.006439,-0.029215,-0.003403,NaN,0.352439,1.000000,0.018105,0.005372,...,-0.044055,0.003954,-0.015218,0.027890,0.023327,0.014828,-0.009080,0.003954,-0.052503,-0.038105
EMAIL_ID,-0.037923,0.025776,0.122320,0.166749,-0.118268,NaN,-0.009594,0.018105,1.000000,0.035098,...,-0.028050,-0.024397,0.003442,0.017429,0.009196,0.050633,0.064003,0.034292,-0.040874,0.021158
Family_Members,0.016950,0.890248,0.050957,0.266527,-0.238705,NaN,0.072228,0.005372,0.035098,1.000000,...,0.044543,0.004901,0.055483,0.045989,0.001665,0.031831,0.000752,-0.004067,0.005206,-0.009703
GENDER_F,-0.024617,-0.061377,-0.220245,-0.187077,0.176552,NaN,-0.040825,0.031592,0.023626,-0.097558,...,-0.231277,-0.046723,-0.092014,0.132883,0.068177,0.027650,0.135540,0.058787,-0.092421,0.043760
GENDER_M,0.027597,0.063068,0.209820,0.183867,-0.176383,NaN,0.042434,-0.036990,-0.025321,0.099406,...,0.236158,0.047559,0.090425,-0.131507,-0.067362,-0.027382,-0.138115,-0.058219,0.093858,-0.043337
Car_Owner_N,0.046811,-0.063467,-0.211199,-0.145186,0.150658,NaN,-0.029856,-0.031096,-0.038007,-0.119851,...,-0.062545,0.045521,-0.093873,0.016053,0.023412,0.029557,0.074187,0.045521,0.032153,0.023570
Car_Owner_Y,-0.046811,0.063467,0.211199,0.145186,-0.150658,NaN,0.029856,0.031096,0.038007,0.119851,...,0.062545,-0.045521,0.093873,-0.016053,-0.023412,-0.029557,-0.074187,-0.045521,-0.032153,-0.023570
Propert_Owner_N,0.050421,0.003352,-0.044199,0.125150,-0.100686,NaN,0.170760,0.080780,-0.064180,0.004458,...,0.024589,-0.020126,-0.030028,0.035471,-0.011823,0.011515,0.023157,-0.020126,-0.018173,0.006271
Propert_Owner_Y,-0.050421,-0.003352,0.044199,-0.125150,0.100686,NaN,-0.170760,-0.080780,0.064180,-0.004458,...,-0.024589,0.020126,0.030028,-0.035471,0.011823,-0.011515,-0.023157,0.020126,0.018173,-0.006271
Type_Income_Commercial associate,0.005926,0.059449,0.210958,0.179411,-0.248604,NaN,-0.018461,-0.016271,0.080318,0.061120,...,-0.036969,0.017573,0.112531,-0.024011,0.043684,0.064752,0.102984,-0.002444,0.013344,0.048841
Type_Income_Pensioner,-0.060256,-0.217467,-0.146734,-0.613142,0.981839,NaN,-0.226629,0.006502,-0.099206,-0.232919,...,-0.209847,-0.012646,-0.136306,-0.074143,-0.048326,-0.016495,-0.134141,-0.035071,-0.058757,-0.026106
Type_Income_State servant,0.015238,0.035128,0.050745,0.060809,-0.131034,NaN,0.011309,0.000562,0.070197,0.042123,...,-0.071869,-0.021765,0.033012,0.183929,0.017094,-0.010237,-0.083249,0.042780,-0.036465,-0.016202
Type_Income_Working,0.032624,0.095880,-0.094410,0.279762,-0.464229,NaN,0.181551,0.008595,-0.029986,0.102490,...,0.228368,0.006129,-0.009628,-0.020290,-0.009471,-0.037101,0.058089,0.006129,0.052426,-0.013156
EDUCATION_Academic degree,-0.034104,0.027202,0.014356,0.008725,-0.016847,NaN,-0.018433,0.014828,-0.011475,0.012850,...,-0.016458,-0.002751,-0.011163,-0.006571,-0.003790,-0.001294,-0.010520,-0.002751,-0.004608,-0.002047
EDUCATION_Higher education,-0.026715,0.052443,0.248708,0.143764,-0.110300,NaN,-0.009310,0.019344,0.113131,0.056793,...,-0.144323,-0.047121,0.227751,-0.022578,-0.023293,-0.022162,-0.024552,-0.009070,-0.010096,0.015908
EDUCATION_Incomplete higher,0.029541,0.036255,0.006902,0.159281,-0.070678,NaN,0.084305,0.020175,0.040479,0.023349,...,-0.023099,-0.016392,0.022558,-0.021331,-0.022587,-0.007710,-0.015901,0.066531,-0.002455,-0.012202
EDUCATION_Lower secondary,0.005147,-0.012001,-0.056136,-0.016399,0.052027,NaN,-0.018825,0.006064,0.020444,-0.002307,...,-0.024141,-0.008968,-0.016668,-0.021425,-0.012357,-0.004218,0.027875,-0.008968,-0.015025,-0.006676
EDUCATION_Secondary / secondary special,0.013797,-0.064543,-0.225662,-0.201923,0.123682,NaN,-0.021795,-0.029701,-0.128858,-0.064339,...,0.153879,0.054152,-0.220532,0.036405,0.035192,0.025470,0.024123,-0.017911,0.014664,-0.007969
Marital_status_Civil marriage,0.023198,-0.002331,0.003265,0.056384,-0.056262,NaN,-0.006503,-0.018406,0.006052,0.068161,...,0.024296,0.048609,-0.017311,0.010915,-0.002740,0.063318,0.019805,0.014203,0.007655,0.031061
Marital_status_Married,-0.032530,0.145940,-0.021976,0.042554,-0.088263,NaN,0.091253,0.028125,0.033873,0.501229,...,0.030650,-0.038157,0.038278,0.040009,-0.046684,-0.013671,-0.034231,-0.038157,0.011610,-0.009457
Marital_status_Separated,0.007515,0.001284,-0.000445,-0.084887,0.034051,NaN,-0.052587,0.013295,0.019719,-0.202138,...,-0.011469,0.015567,-0.041954,0.028773,0.050006,-0.009248,0.014256,-0.019663,-0.011695,0.032567
Marital_status_Single / not married,0.013948,-0.133364,0.067685,0.111604,-0.030003,NaN,-0.045974,-0.068110,-0.025035,-0.415664,...,0.003380,0.016339,-0.012535,-0.055076,0.043931,-0.014910,0.048187,0.040359,-0.009649,-0.023597
Marital_status_Widow,0.012707,-0.096715,-0.065988,-0.245207,0.268019,NaN,-0.056341,0.057227,-0.061597,-0.257568,...,-0.087347,-0.017256,0.004367,-0.041225,-0.023777,-0.008116,-0.043669,0.022317,-0.005042,-0.012845
Housing_type_Co-op apartment,0.043241,-0.030264,-0.040881,-0.015443,-0.026114,NaN,0.054976,0.035782,-0.018161,-0.069784,...,-0.026047,-0.004353,-0.017667,-0.010400,-0.005998,-0.002047,-0.016650,-0.004353,-0.007293,-0.003240
Housing_type_House / apartment,-0.060418,0.025007,0.009727,-0.168432,0.061684,NaN,-0.046329,0.035873,-0.010620,0.046321,...,0.000468,0.026682,0.034920,0.016756,0.016838,0.012549,-0.067519,0.026682,-0.021202,0.019862
Housing_type_Municipal apartment,0.065992,-0.045196,-0.040173,-0.008409,0.067241,NaN,0.008538,-0.018444,0.001276,-0.077088,...,-0.020429,-0.014399,-0.058435,-0.014305,-0.019841,-0.006772,0.050405,-0.014399,0.004060,-0.010718
Housing_type_Office apartment,0.015547,0.003118,0.045326,-0.019197,-0.034679,NaN,0.002678,-0.032808,-0.024397,0.013869,...,0.032380,-0.005848,0.006282,-0.013971,-0.008058,-0.002751,-0.022368,-0.005848,0.192426,-0.004353
Housing_type_Rented apartment,0.005193,-0.012001,0.020979,0.084386,-0.037385,NaN,-0.005066,-0.018097,0.020444,0.003587,...,0.005377,-0.008968,-0.036395,-0.021425,-0.012357,-0.004218,0.007149,-0.008968,-0.015025,-0.006676
Housing_type_With parents,0.011548,0.014946,0.003021,0.209210,-0.103760,NaN,0.045718,-0.023701,0.016223,0.009486,...,0.008868,-0.017852,0.020323,0.006867,0.003400,-0.008396,0.061677,-0.017852,-0.029909,-0.013289
Type_Occupation_Accountants,-0.021016,0.009198,0.031659,0.053410,-0.076876,NaN,0.027272,0.011647,0.052833,0.028285,...,-0.078265,-0.013080,-0.053083,-0.031249,-0.018024,-0.006152,-0.050029,-0.013080,-0.021914,-0.009737
Type_Occupation_Cleaning staff,0.014727,-0.007601,-0.070600,-0.008647,-0.054545,NaN,0.059484,0.002273,-0.000609,-0.008946,...,-0.054941,-0.009182,-0.037264,-0.021936,-0.012652,-0.004319,-0.035120,-0.009182,-0.015383,-0.006835
Type_Occupation_Cooking staff,-0.003634,-0.026385,-0.041621,-0.007826,-0.053051,NaN,0.036209,0.018144,0.001159,-0.019989,...,-0.053660,-0.008968,-0.036395,-0.021425,-0.012357,-0.004218,-0.034301,-0.008968,-0.015025,-0.006676
Type_Occupation_Core staff,0.003680,0.050506,-0.007293,0.132979,-0.160975,NaN,0.059489,0.022825,0.091300,0.030003,...,-0.162833,-0.027213,-0.110442,-0.065015,-0.037499,-0.012799,-0.104088,-0.027213,-0.045593,-0.020257
Type_Occupation_Drivers,-0.006072,0.070828,0.081706,0.058002,-0.107920,NaN,0.021617,-0.015930,-0.048157,0.086651,...,-0.110978,-0.018547,-0.075271,-0.044310,-0.025557,-0.008723,-0.070941,-0.018547,-0.031074,-0.013806
Type_Occupation_HR staff,0.008356,0.033326,-0.016823,0.024157,-0.019366,NaN,-0.022583,-0.029497,-0.014058,0.007992,...,-0.020163,-0.003370,-0.013676,-0.008051,-0.004643,-0.001585,-0.012889,-0.003370,-0.005646,-0.002508
Type_Occupation_High skill tech staff,0.026125,0.013144,0.032090,0.043246,-0.094702,NaN,0.051416,0.047986,-0.000050,0.015306,...,-0.095796,-0.016010,-0.064974,-0.038249,-0.022061,-0.007530,-0.061236,-0.016010,-0.026823,-0.011918
Type_Occupation_IT staff,-0.022648,-0.019122,-0.028135,0.048360,-0.015646,NaN,-0.018433,-0.024076,0.112741,-0.006131,...,-0.016458,-0.002751,-0.011163,-0.006571,-0.003790,-0.001294,-0.010520,-0.002751,-0.004608,-0.002047
Type_Occupation_Laborers,-0.001947,0.022808,-0.024740,0.132580,-0.206216,NaN,0.013685,-0.044055,-0.028050,0.044543,...,1.000000,-0.034992,-0.142009,-0.083597,-0.048217,-0.016458,-0.133839,-0.034992,-0.058625,-0.026047
Type_Occupation_Low-skill Laborers,-0.001929,-0.007826,-0.040765,0.002079,-0.034020,NaN,0.044546,0.003954,-0.024397,0.004901,...,-0.034992,1.000000,-0.023733,-0.013971,-0.008058,-0.002751,-0.022368,-0.005848,-0.009798,-0.004353
Type_Occupation_Managers,0.006502,0.052493,0.277783,0.104158,-0.139870,NaN,0.032106,-0.015218,0.003442,0.055483,...,-0.142009,-0.023733,1.000000,-0.056700,-0.032703,-0.011163,-0.090776,-0.023733,-0.039762,-0.017667
Type_Occupation_Medicine staff,0.044050,0.029932,-0.052991,-0.015466,-0.085226,NaN,-0.003606,0.027890,0.017429,0.045989,...,-0.083597,-0.013971,-0.056700,1.000000,-0.019252,-0.006571,-0.053438,-0.013971,-0.023407,-0.010400
Type_Occupation_Private service staff,0.066078,0.031794,0.008424,0.027886,-0.047977,NaN,0.007083,0.023327,0.009196,0.001665,...,-0.048217,-0.008058,-0.032703,-0.019252,1.000000,-0.003790,-0.030822,-0.008058,-0.013501,-0.005998
Type_Occupation_Realty agents,0.018468,0.027202,0.003553,0.041609,-0.016329,NaN,0.025875,0.014828,0.050633,0.031831,...,-0.016458,-0.002751,-0.011163,-0.006571,-0.003790,1.000000,-0.010520,-0.002751,-0.004608,-0.002047
Type_Occupation_Sales staff,0.006714,0.017414,-0.031391,0.143097,-0.129966,NaN,0.003678,-0.009080,0.064003,0.000752,...,-0.133839,-0.022368,-0.090776,-0.053438,-0.030822,-0.010520,1.000000,-0.022368,-0.037475,-0.016650
Type_Occupation_Secretaries,0.023849,0.014061,-0.019668,0.002621,-0.034856,NaN,0.002678,0.003954,0.034292,-0.004067,...,-0.034992,-0.005848,-0.023733,-0.013971,-0.008058,-0.002751,-0.022368,1.000000,-0.009798,-0.004353
Type_Occupation_Security staff,0.064955,-0.002111,-0.010219,-0.042135,-0.056413,NaN,-0.015155,-0.052503,-0.040874,0.005206,...,-0.058625,-0.009798,-0.039762,-0.023407,-0.013501,-0.004608,-0.037475,-0.009798,1.000000,-0.007293
Type_Occupation_Waiters/barmen staff,0.035227,-0.015601,-0.034954,0.041152,-0.025315,NaN,-0.001123,-0.038105,0.021158,-0.009703,...,-0.026047,-0.004353,-0.017667,-0.010400,-0.005998,-0.002047,-0.016650,-0.004353,-0.007293,1.000000

In [8]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

credit_df_encoded.isnull().sum()

Ind_ID                                      0
CHILDREN                                    0
Annual_income                              23
Birthday_count                             22
Employed_days                               0
Mobile_phone                                0
Work_Phone                                  0
Phone                                       0
EMAIL_ID                                    0
Family_Members                              0
GENDER_F                                    0
GENDER_M                                    0
Car_Owner_N                                 0
Car_Owner_Y                                 0
Propert_Owner_N                             0
Propert_Owner_Y                             0
Type_Income_Commercial associate            0
Type_Income_Pensioner                       0
Type_Income_State servant                   0
Type_Income_Working                         0
EDUCATION_Academic degree                   0
EDUCATION_Higher education                  0
EDUCATION_Incomplete higher                 0
EDUCATION_Lower secondary                   0
EDUCATION_Secondary / secondary special     0
Marital_status_Civil marriage               0
Marital_status_Married                      0
Marital_status_Separated                    0
Marital_status_Single / not married         0
Marital_status_Widow                        0
Housing_type_Co-op apartment                0
Housing_type_House / apartment              0
Housing_type_Municipal apartment            0
Housing_type_Office apartment               0
Housing_type_Rented apartment               0
Housing_type_With parents                   0
Type_Occupation_Accountants                 0
Type_Occupation_Cleaning staff              0
Type_Occupation_Cooking staff               0
Type_Occupation_Core staff                  0
Type_Occupation_Drivers                     0
Type_Occupation_HR staff                    0
Type_Occupation_High skill tech staff       0
Type_Occupation_IT staff                    0
Type_Occupation_Laborers                    0
Type_Occupation_Low-skill Laborers          0
Type_Occupation_Managers                    0
Type_Occupation_Medicine staff              0
Type_Occupation_Private service staff       0
Type_Occupation_Realty agents               0
Type_Occupation_Sales staff                 0
Type_Occupation_Secretaries                 0
Type_Occupation_Security staff              0
Type_Occupation_Waiters/barmen staff        0
dtype: int64

In [9]:

X = np.array(credit_df_encoded['Employed_days']).reshape(-1,1)
y = np.array(credit_df_encoded['Type_Income_Pensioner']).reshape(-1, 1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 42)

# 'Employed_days','Type_Income_Pensioner'

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train) 
X_test = sc.fit_transform(X_test)

knn = KNeighborsClassifier(n_neighbors=13) 
knn.fit(X_train, y_train) 

y_pred = knn.predict(X_test)
print(y_pred)
print(type(y_pred))

[0 1 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 1 0 0 0 1 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1
 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0
 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 0 1 0 0
 1 1 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0]
<class 'numpy.ndarray'>

/opt/homebrew/Cellar/jupyterlab/4.2.5/libexec/lib/python3.12/site-packages/sklearn/neighbors/_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

In [10]:
print(knn.score(X_test, y_test))

0.9978494623655914

In [11]:
import pandas as pd
from sklearn.feature_selection import VarianceThreshold


credit_df_encoded.fillna(credit_df_encoded.median(), inplace=True)


credit_df_encoded = pd.get_dummies(credit_df_encoded, drop_first=True)


threshold = 0.1
selector = VarianceThreshold(threshold=threshold)


credit_df_reduced = selector.fit_transform(credit_df_encoded)


selected_features = credit_df_encoded.columns[selector.get_support()]


print("Features after Variance :", selected_features)
print("Reduced Shape:", credit_df_reduced.shape)

Features after Variance : Index(['Ind_ID', 'CHILDREN', 'Annual_income', 'Birthday_count',
       'Employed_days', 'Work_Phone', 'Phone', 'Family_Members', 'GENDER_F',
       'GENDER_M', 'Car_Owner_N', 'Car_Owner_Y', 'Propert_Owner_N',
       'Propert_Owner_Y', 'Type_Income_Commercial associate',
       'Type_Income_Pensioner', 'Type_Income_Working',
       'EDUCATION_Higher education', 'EDUCATION_Secondary / secondary special',
       'Marital_status_Married', 'Marital_status_Single / not married',
       'Type_Occupation_Laborers'],
      dtype='object')
Reduced Shape: (1548, 22)

In [28]:
print(knn.score(X_test, y_test))

0.9978494623655914

In [ ]:
# When comparing the orginal dataset and the data set after being reshaped , I found that the accuracy score stayed the same.